name: TechTrends - Package with Docker
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.UDACITY_TECH_TRENDS_DOCKER_ID }}
          password: ${{ secrets.UDACITY_TECH_TRENDS_DOCKER_SECRET }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./project
          file: ./project/Dockerfile
          push: true
          tags: ${{ secrets.UDACITY_TECH_TRENDS_DOCKER_ID }}/techtrends:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}